# Generated by Django 6.0.3 on 2026-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_driver_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profile_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль'),
        ),
    ]
